# Generated by Django 2.2.13 on 2021-01-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210124_1634'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodsinfo',
            table='goods_goodsinfo',
        ),
    ]
