# Generated by Django 2.2.13 on 2021-01-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20210124_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={},
        ),
    ]
