# Generated by Django 2.2.13 on 2021-01-31 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20210131_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_cag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.GoodsCategory'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_img',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_price',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='goodsinfo',
            table=None,
        ),
    ]
