# Generated by Django 2.2.13 on 2021-01-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderGoods',
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
